FROM python:3.9-slim

WORKDIR /app

# Copy the requirements file first
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . /app

# Define the command to run our application
CMD [ "python", "code/training_pipeline/data_ingestion.py" ]
