FROM node:14-alpine

WORKDIR /app

COPY react_frontend/package*.json ./

RUN npm install

COPY react_frontend .

ARG REACT_APP_API_URL

ENV PORT=3001
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

RUN npm run build

EXPOSE 3001

CMD ["npm", "start"]